# Board size
BOARD_X_SIZE = 4
BOARD_Y_SIZE = 4

# Players color
NONE_PLAYER = None
BLACK_PLAYER = True
WHITE_PLAYER = False

# Orientations
VERTICAL_ORIENTATION = "v"
HORIZONTAL_ORIENTATION = "h"
NONE_ORIENTATION = "-"

# Players orientation
PLAYERS_ORIENTATION = {BLACK_PLAYER: VERTICAL_ORIENTATION,
                       WHITE_PLAYER: HORIZONTAL_ORIENTATION}

# Players name
PLAYERS_NAME = {BLACK_PLAYER: 'BLACK PLAYER',
                WHITE_PLAYER: 'WHITE PLAYER'}

# MCTS training epochs
TRAINING_EPOCHS = 50
