# Board size
BOARD_X_SIZE = 3
BOARD_Y_SIZE = 3

# Players color
NONE_PLAYER = None
BLACK_PLAYER = True
WHITE_PLAYER = False

# Orientations
VERTICAL_ORIENTATION = "v"
HORIZONTAL_ORIENTATION = "h"
NONE_ORIENTATION = "-"

# Players orientations
PLAYERS_ORIENTATION = {BLACK_PLAYER: VERTICAL_ORIENTATION,
                       WHITE_PLAYER: HORIZONTAL_ORIENTATION}
