# Board size
BOARD_X_SIZE = 8
BOARD_Y_SIZE = 8

# Players colors
NONE_PLAYER  = 0
BLACK_PLAYER = 1
WHITE_PLAYER = 2

# Orientations
VERTICAL_ORIENTATION    = "v"
HORIZONTAL_ORIENTATION  = "h"
NONE_ORIENTATION        = " "

# Players orientations
PLAYERS_ORIENTATION    = {BLACK_PLAYER:VERTICAL_ORIENTATION,
                            WHITE_PLAYER:HORIZONTAL_ORIENTATION}